MetadadoAeroporto = tuple[str, str | None, str, bool, str | None]

ESTADOS_BRASIL: dict[str, str] = {
    "AC": "Acre",
    "AL": "Alagoas",
    "AP": "Amapá",
    "AM": "Amazonas",
    "BA": "Bahia",
    "CE": "Ceará",
    "DF": "Distrito Federal",
    "ES": "Espírito Santo",
    "GO": "Goiás",
    "MA": "Maranhão",
    "MT": "Mato Grosso",
    "MS": "Mato Grosso do Sul",
    "MG": "Minas Gerais",
    "PA": "Pará",
    "PB": "Paraíba",
    "PR": "Paraná",
    "PE": "Pernambuco",
    "PI": "Piauí",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RS": "Rio Grande do Sul",
    "RO": "Rondônia",
    "RR": "Roraima",
    "SC": "Santa Catarina",
    "SP": "São Paulo",
    "SE": "Sergipe",
    "TO": "Tocantins",
}

MAPEAMENTO_AEROPORTOS: dict[str, MetadadoAeroporto] = {
    "VIX": ("Vitória", "ES", "Brasil", True, "Aeroporto de Vitória — principal aeroporto comercial do Espírito Santo"),
    "GRU": (
        "São Paulo",
        "SP",
        "Brasil",
        True,
        "Aeroporto Internacional de Guarulhos — maior hub de voos nacionais e internacionais de SP",
    ),
    "CGH": (
        "São Paulo",
        "SP",
        "Brasil",
        True,
        "Aeroporto de Congonhas — próximo ao centro de SP, foco em ponte aérea e voos nacionais",
    ),
    "VCP": (
        "Campinas",
        "SP",
        "Brasil",
        True,
        "Aeroporto de Viracopos (Campinas) — hub principal da Azul Linhas Aéreas em SP",
    ),
    "GIG": (
        "Rio de Janeiro",
        "RJ",
        "Brasil",
        True,
        "Aeroporto Internacional do Galeão — voos internacionais e conexões no RJ",
    ),
    "SDU": (
        "Rio de Janeiro",
        "RJ",
        "Brasil",
        True,
        "Aeroporto Santos Dumont — próximo ao centro do RJ, ponte aérea com SP",
    ),
    "CNF": (
        "Belo Horizonte",
        "MG",
        "Brasil",
        True,
        "Aeroporto Internacional de Confins — maior hub de voos comerciais de MG",
    ),
    "PLU": (
        "Belo Horizonte",
        "MG",
        "Brasil",
        False,
        "Aeroporto da Pampulha — voos executivos e regionais, poucas opções comerciais",
    ),
    "SSA": (
        "Salvador",
        "BA",
        "Brasil",
        True,
        "Aeroporto Internacional de Salvador — principal porta de entrada da Bahia",
    ),
    "REC": ("Recife", "PE", "Brasil", True, "Aeroporto Internacional do Recife — hub de conexões do Nordeste"),
    "FOR": ("Fortaleza", "CE", "Brasil", True, "Aeroporto Internacional de Fortaleza — hub comercial do Ceará"),
    "BSB": (
        "Brasília",
        "DF",
        "Brasil",
        True,
        "Aeroporto Internacional de Brasília — hub central de conexões no Brasil",
    ),
    "CWB": ("Curitiba", "PR", "Brasil", True, "Aeroporto Internacional Afonso Pena (Curitiba) — principal de PR"),
    "POA": (
        "Porto Alegre",
        "RS",
        "Brasil",
        True,
        "Aeroporto Internacional Salgado Filho (Porto Alegre) — principal de RS",
    ),
    "FLN": (
        "Florianópolis",
        "SC",
        "Brasil",
        True,
        "Aeroporto Internacional Hercílio Luz (Florianópolis) — principal de SC",
    ),
    "MAO": ("Manaus", "AM", "Brasil", True, "Aeroporto Internacional de Manaus — principal hub da Região Norte"),
    "BEL": ("Belém", "PA", "Brasil", True, "Aeroporto Internacional de Belém — conexões do Pará e Região Norte"),
    "GYN": ("Goiânia", "GO", "Brasil", True, "Aeroporto Santa Genoveva (Goiânia) — principal aeroporto de Goiás"),
    "CLV": ("Caldas Novas", "GO", "Brasil", True, "Aeroporto de Caldas Novas — voos turísticos e regionais"),
    "RRV": ("Rio Verde", "GO", "Brasil", False, "Aeroporto de Rio Verde — aviação regional e executiva"),
    "CGB": ("Cuiabá", "MT", "Brasil", True, "Aeroporto Internacional de Cuiabá — principal de MT"),
    "NAT": ("Natal", "RN", "Brasil", True, "Aeroporto Internacional de Natal — principal de RN"),
    "MCZ": ("Maceió", "AL", "Brasil", True, "Aeroporto Internacional de Maceió — principal de AL"),
    "JPA": ("João Pessoa", "PB", "Brasil", True, "Aeroporto Internacional de João Pessoa — principal de PB"),
    "AJU": ("Aracaju", "SE", "Brasil", True, "Aeroporto de Aracaju — principal de SE"),
    "NVT": (
        "Navegantes",
        "SC",
        "Brasil",
        True,
        "Aeroporto de Navegantes — acesso a Balneário Camboriú e Vale do Itajaí",
    ),
    "JOI": ("Joinville", "SC", "Brasil", True, "Aeroporto de Joinville — voos comerciais em SC"),
    "IGU": (
        "Foz do Iguaçu",
        "PR",
        "Brasil",
        True,
        "Aeroporto Internacional de Foz do Iguaçu — voos turísticos na tríplice fronteira",
    ),
    "LDB": ("Londrina", "PR", "Brasil", True, "Aeroporto de Londrina — voos comerciais no norte do PR"),
    "UDI": ("Uberlândia", "MG", "Brasil", True, "Aeroporto de Uberlândia — principal hub do Triângulo Mineiro"),
    "RAO": ("Ribeirão Preto", "SP", "Brasil", True, "Aeroporto de Ribeirão Preto — voos comerciais no interior de SP"),
    "BPS": ("Porto Seguro", "BA", "Brasil", True, "Aeroporto de Porto Seguro — voos turísticos no sul da Bahia"),
    "VDC": (
        "Vitória da Conquista",
        "BA",
        "Brasil",
        True,
        "Aeroporto de Vitória da Conquista — voos no sudoeste baiano",
    ),
    "IOS": ("Ilhéus", "BA", "Brasil", True, "Aeroporto de Ilhéus — voos turísticos no litoral baiano"),
    "MCP": ("Macapá", "AP", "Brasil", True, "Aeroporto de Macapá — principal do Amapá"),
    "BVB": ("Boa Vista", "RR", "Brasil", True, "Aeroporto de Boa Vista — principal de Roraima"),
    "RBR": ("Rio Branco", "AC", "Brasil", True, "Aeroporto de Rio Branco — principal do Acre"),
    "PVH": ("Porto Velho", "RO", "Brasil", True, "Aeroporto de Porto Velho — principal de Rondônia"),
    "PMW": ("Palmas", "TO", "Brasil", True, "Aeroporto de Palmas — principal do Tocantins"),
    "SLZ": ("São Luís", "MA", "Brasil", True, "Aeroporto de São Luís — principal do Maranhão"),
    "THE": ("Teresina", "PI", "Brasil", True, "Aeroporto de Teresina — principal do Piauí"),
    "IMP": ("Imperatriz", "MA", "Brasil", True, "Aeroporto de Imperatriz — voos no interior do Maranhão"),
    "PNZ": ("Petrolina", "PE", "Brasil", True, "Aeroporto de Petrolina — voos no Vale do São Francisco"),
    "JDO": ("Juazeiro do Norte", "CE", "Brasil", True, "Aeroporto de Juazeiro do Norte — voos no Cariri cearense"),
    "CPV": ("Campina Grande", "PB", "Brasil", True, "Aeroporto de Campina Grande — voos no interior da Paraíba"),
    "XAP": ("Chapecó", "SC", "Brasil", True, "Aeroporto de Chapecó — principal do oeste catarinense"),
    "CXJ": ("Caxias do Sul", "RS", "Brasil", True, "Aeroporto de Caxias do Sul — voos na serra gaúcha"),
    "EZE": (
        "Buenos Aires",
        None,
        "Argentina",
        True,
        "Aeroporto Internacional de Ezeiza — voos internacionais em Buenos Aires",
    ),
    "AEP": (
        "Buenos Aires",
        None,
        "Argentina",
        True,
        "Aeroparque Jorge Newbery — voos regionais no centro de Buenos Aires",
    ),
    "MVD": ("Montevidéu", None, "Uruguai", True, "Aeroporto Internacional de Carrasco — principal do Uruguai"),
    "SCL": ("Santiago", None, "Chile", True, "Aeroporto Internacional de Santiago — principal do Chile"),
    "LIM": ("Lima", None, "Peru", True, "Aeroporto Internacional Jorge Chávez — principal hub do Peru"),
    "BOG": ("Bogotá", None, "Colômbia", True, "Aeroporto Internacional El Dorado — principal hub da Colômbia"),
    "MIA": ("Miami", "FL", "Estados Unidos", True, "Miami International Airport — principal porta para Flórida"),
    "MCO": ("Orlando", "FL", "Estados Unidos", True, "Orlando International Airport — voos para parques e turismo"),
    "JFK": (
        "Nova York",
        "NY",
        "Estados Unidos",
        True,
        "John F. Kennedy International Airport — maior hub internacional de NY",
    ),
    "LHR": ("Londres", None, "Reino Unido", True, "Heathrow Airport — maior aeroporto de Londres"),
    "CDG": ("Paris", None, "França", True, "Charles de Gaulle Airport — principal de Paris"),
    "MAD": ("Madri", None, "Espanha", True, "Adolfo Suárez Madrid-Barajas Airport — principal da Espanha"),
    "LIS": ("Lisboa", None, "Portugal", True, "Humberto Delgado Airport — principal porta de entrada de Portugal"),
    "FRA": ("Frankfurt", None, "Alemanha", True, "Frankfurt Airport — principal hub da Alemanha"),
}
